baseURL = "http://www.sizeofvoid.com/"
languageCode = "en-us"
title = "sizeof(void)"
googleAnalytics = "UA-45192408-2"

theme = 'cactus'
enableEmoji = true

copyright = "Mathias Westerdahl"

[author]
    name = "Mathias Westerdahl"

[permalinks]
    posts = "/:year/:month/:day/:slug/"
    categories = "/category/:slug/"      # required
    tags = "/tag/:slug/"                 # required
    pages = "/:slug/"

[sitemap]                    # required
    changefreq = "weekly"
    priority = 0.5
    filename = "sitemap.xml"

[taxonomies]
    author = "authors"
    category = "categories"
    tag = "tags"
    archive = "archives"

[params]
    description = "A blog about programming bits and bobs"
    images = ["/images/logo.png"]
    logoTitle = "sizeof(void)"
    headerImage = "https://d3n1faj5cqbhy8.cloudfront.net/images/background.jpg"
    customFavicon = "https://d3n1faj5cqbhy8.cloudfront.net/favicon.ico"
    dateFormatToUse = "2006-01-02"
    showAuthorCard = true # Whether to show author information below the article
    logo = "/images/logo.png"
    customCSS = ["custom.css"]
    mainSection = "posts"
    showAllPostsOnHomePage = true
    postsOnHomePage = 15
    tagsOverview = true
    rss = false
    mathjax = true



[[params.social]]
    name = "github"
    link = "https://github.com/jcash"

[[params.social]]
    name = "twitter"
    link = "https://twitter.com/mwesterdahl76"

[[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/jcash/"

[[menu.main]]
    name = "All"
    url = "/posts"
    weight = 2

[[menu.main]]
    name = "Programming"
    url = "/category/programming"
    weight = 3

[[menu.main]]
    name = "Whoami"
    url = "/about"
    weight = 4

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4


